"""add payment fields

Revision ID: ac39a83deb73
Revises: 
Create Date: 2025-12-07 14:49:54.852538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac39a83deb73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('set_by_user_id', sa.Integer(), nullable=False),
    sa.Column('set_by_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=True)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.add_column('payments', sa.Column('bank', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('amount_secondary', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('change_usd', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('change_secondary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'change_secondary')
    op.drop_column('payments', 'change_usd')
    op.drop_column('payments', 'amount_secondary')
    op.drop_column('payments', 'exchange_rate')
    op.drop_column('payments', 'bank')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
